allowed-entities:
  - PIG
  - COW
  - CHICKEN
  - BEE
  - TURTLE
  - SALMON
  - SHEEP

member-upgrade:
  default-member:
    next: m1
    amount: 2
    price: 1000
  m1:
    next: m2
    amount: 3
    price: 10000
  m2:
    next: m3
    amount: 4
    price: 100000
  m3:
    next: m4
    amount: 5
    price: 1000000

border-upgrade:
  default-border:
    next: b1
    amount: 50
    price: 10000
  b1:
    next: b2
    amount: 60
    price: 100000
  b2:
    next: b3
    amount: 70
    price: 100000
  b3:
    next: b4
    amount: 80
    price: 100000
  b4:
    next: b5
    amount: 90
    price: 100000
  b5:
    next: b6
    amount: 100
    price: 100000

animal-upgrade:
  default-animal:
    next: a1
    amount: 5
    price: 10
  a1:
    next: a2
    amount: 7
    price: 12
  a2:
    next: a3
    amount: 9
    price: 11
  a3:
    next: a4
    amount: 11
    price: 13
  a4:
    next: a5
    amount: 13
    price: 15
  a5:
    next: a6
    amount: 15
    price: 17